FROM default-route-openshift-image-registry.apps.ocd1.shinhan.local/openshift/ubi8-openjdk-11-runtime:1.10
USER jboss
COPY ./spring-boot-hello-1.0.jar spring-boot-hello-1.0.jar
CMD java -jar spring-boot-hello-1.0.jar
